name: Turnout Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch: # Allows manual runs in GitHub Actions

jobs:
  scrape_turnout:
    runs-on: windows-latest  # Uses Windows runner since R is already installed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Turnout Scraper in R
        run: Rscript scripts/turnout_scraper.R
        shell: cmd
        timeout-minutes: 60  # Set timeout based on expected runtime
