name: Turnout Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch: # Allows manual runs in GitHub Actions

jobs:
  scrape_turnout:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "us-east-1"  # Specify your region
        shell: pwsh
        
      - name: Run Turnout Scraper by County in R
        run: |
          Rscript scripts/turnout_scraper.R
        shell: cmd
        timeout-minutes: 60
        
  scrape_turnout_precinct:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set region "us-east-1"  # Specify your region
        shell: pwsh

      - name: Run Turnout Scraper by Precinct in R
        run: |
          Rscript scripts/turnout_scraper_by_precinct.R
        shell: cmd
        timeout-minutes: 60
