name: Turnout Scraper
on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch: # Allows manual runs in GitHub Actions

jobs:
  scrape_turnout:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI (if not already installed)
        shell: pwsh
        run: |
          if (!(Test-Path "C:\Program Files\Amazon\AWSCLI")) {
            Write-Output "Installing AWS CLI..."
            Start-Process msiexec.exe -ArgumentList '/i https://awscli.amazonaws.com/AWSCLIV2.msi /qn' -Wait
          } else {
            Write-Output "AWS CLI is already installed."
          }
          aws --version

      - name: Set up R environment with required packages
        run: |
          # Install required R packages
          Rscript -e "if (!requireNamespace('googlesheets4', quietly = TRUE)) install.packages('googlesheets4', repos='http://cran.rstudio.com/')"
          Rscript -e "if (!requireNamespace('httr', quietly = TRUE)) install.packages('httr', repos='http://cran.rstudio.com/')"
          Rscript -e "if (!requireNamespace('jsonlite', quietly = TRUE)) install.packages('jsonlite', repos='http://cran.rstudio.com/')"
          Rscript -e "if (!requireNamespace('tidyverse', quietly = TRUE)) install.packages('tidyverse', repos='http://cran.rstudio.com/')"
          Rscript -e "if (!requireNamespace('scales', quietly = TRUE)) install.packages('scales', repos='http://cran.rstudio.com/')"
          Rscript -e "if (!requireNamespace('lubridate', quietly = TRUE)) install.packages('lubridate', repos='http://cran.rstudio.com/')"

      - name: Run Turnout Scraper in R
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          Rscript scripts/turnout_scraper.R
        shell: cmd
        timeout-minutes: 60
