name: Turnout Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch: # Allows manual runs in GitHub Actions

jobs:
  scrape_turnout:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R environment with required packages
        run: |
          Rscript -e 'packages <- c("googlesheets4", "httr", "jsonlite", "tidyverse", "scales", "lubridate", "conflicted"); new_packages <- packages[!(packages %in% installed.packages()[,"Package"])]; if(length(new_packages)) install.packages(new_packages, repos="http://cran.rstudio.com/")'

      - name: Run Turnout Scraper in R
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          Rscript scripts/turnout_scraper.R
        shell: cmd
        timeout-minutes: 60
